### ISSUE TITLE
Could you release experimental settings for every datasets?

### ISSUE THREAD

**Issue by xtianxy** [chen1310054465/SBN#3]
Thank you for publishing the code! I want to reproduce this experiment and try to obtain the same results in the paper. If experimental settings was released, it should be helpful!

**Comment by chen1310054465** [comment]
You can just refer to the original paper for the experimental settings. In my case, the experimental settings for different data sets are consistent with the default settings of the code.

**Comment by xtianxy** [comment]
> You can just refer to the original paper for the experimental settings. In my case, the experimental settings for different data sets are consistent with the default settings of the code.

Thanks!
