### ISSUE TITLE
This line of code affects the recurrence result

### ISSUE THREAD

**Issue by xtianxy** [chen1310054465/SBN#4]
https://github.com/chen1310054465/SBN/blob/42afdcc44a4384d4048b3f62162196e12116bf18/models/Metric.py#L138
When I annotate this line of code, the metric is very close to that in the paper. It may be debugging code.

**Comment by YllYhj** [comment]
>
Hello, what is your PyTorch version and CUDA version respectively?

**Comment by xtianxy** [comment]
> > 
> 
> Hello, what is your PyTorch version and CUDA version respectively?

pytorch                   1.11.0          py3.7_cuda11.3_cudnn8.2.0_0

**Comment by YllYhj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by YllYhj** [comment]
> > > 
> > 
> > 
> > Hello, what is your PyTorch version and CUDA version respectively?
> 
> pytorch 1.11.0 py3.7_cuda11.3_cudnn8.2.0_0

Many thanks

**Comment by YllYhj** [comment]
UnboundLocalError: local variable 'best_triple_precision' referenced before assignment
你好，请问这个问题您是如何解决的？

**Comment by chen1310054465** [comment]
> https://github.com/chen1310054465/SBN/blob/42afdcc44a4384d4048b3f62162196e12116bf18/models/Metric.py#L138
> 
> 
> When I annotate this line of code, the metric is very close to that in the paper. It may be debugging code.

Sorry for the inconvenience. This code is for experiment and can be deleted during reproduction
