### ISSUE TITLE
How can I solve this problem? Thank you!

### ISSUE THREAD

**Issue by YllYhj** [chen1310054465/SBN#5]
UnboundLocalError: local variable 'best_triple_precision' referenced before assignment

**Comment by zhouyi964007968** [comment]
修改模型变量名

**Comment by YllYhj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
