### ISSUE TITLE
以下是我的复现结果，为什么好像和原文差很多，但是在15RES又特别高

### ISSUE THREAD

**Issue by zhouyi964007968** [chen1310054465/SBN#6]
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

  | P | R | F1
-- | -- | -- | --
14LAP | 0.50 | 0.61 | 0.55
14RES | 0.61 | 0.56 | 0.58
15RES | 0.81 | 0.87 | 0.84
16RES | 0.62 | 0.53 | 0.57

</body>

</html>

**Comment by chen1310054465** [comment]
感谢您关注我的工作。需要注意的是，目前的代码中含有许多在论文中做实验留下的实验代码，时间有点长我也记不得哪些代码还保留着忘了注释，可能需要您仔细核对编码与解码部分，可能仅仅是简单的几行多余的代码就会让结果天差地别。您可以在issue中找到有些网友已经找到的部分实验痕迹。

**Comment by zhouyi964007968** [comment]
好的，感谢答复

**Comment by ZayIsAllYouNeed** [comment]
> 好的，感谢答复

您好！请问您后来顺利复现出论文上的结果了吗？
