### ISSUE TITLE
验证过程和最终测试的数据集问题

### ISSUE THREAD

**Issue by Jackz123456** [chen1310054465/SBN#8]
您好，复现您的工作的时候发现在run.py文件中，模型训练过程中的验证用的是testset，而训练完成后使用的也是testset，请问对于中间过程的验证需要换成devset吗？
374 aspect_result, opinion_result, apce_result, pair_result, triplet_result = eval(Bert, step_1_model,
                                                                                           step2_forward_model,
                                                                                           step2_reverse_model,
                                                                                           testset, args)
452 eval(Bert, step_1_model, step2_forward_model, step2_reverse_model, testset, args)

**Comment by chen1310054465** [comment]
当然可以，我上传的代码是做了一些消融实验之后的代码，时间长了 注释也没有怎么写，您可以按照您的需求修改


1310054465
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chen1310054465/SBN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 晚上9:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chen1310054465/SBN] 验证过程和最终测试的数据集问题 (Issue #8)





 
您好，复现您的工作的时候发现在run.py文件中，模型训练过程中的验证用的是testset，而训练完成后使用的也是testset，请问对于中间过程的验证需要换成devset吗？
 374 aspect_result, opinion_result, apce_result, pair_result, triplet_result = eval(Bert, step_1_model,
 step2_forward_model,
 step2_reverse_model,
 testset, args)
 452 eval(Bert, step_1_model, step2_forward_model, step2_reverse_model, testset, args)
