### ISSUE TITLE
请问您在训练过程中的验证集是采用哪个数据呀？

### ISSUE THREAD

**Issue by ZayIsAllYouNeed** [chen1310054465/SBN#9]
您好，请问复现过程中需要注意什么吗？
我采用dev作为验证集得到的最佳模型在test数据上达不到论文上的指标（其他issue里提到的问题已经在代码里修改了）。
然后我尝试采用test作为验证集，得到的最佳模型在四个数据集上得到的指标(f1 score, %)分别为：14lap: 62.17, 14res: 74.37, 15res: 63.36, 16res: 72.37，其中 15res 差的较多(paper上 64.82)。

**Comment by chen1310054465** [comment]
您好，由于源数据集并没有切分验证集，而我本人在切分数据集时使用了随机种子切分，所以大家在复现的过程中可能存在较大差别。但是从大部分人的反馈和我自己的实验来看，文章的指标并无夸大。您可能需要认真检查代码后重新复现（这是因为代码久远，我记不得在哪里插入过消融实验的代码了，所以您可能正在运行消融实验）

**Comment by ZayIsAllYouNeed** [comment]
> 您好，由于源数据集并没有切分验证集，而我本人在切分数据集时使用了随机种子切分，所以大家在复现的过程中可能存在较大差别。但是从大部分人的反馈和我自己的实验来看，文章的指标并无夸大。您可能需要认真检查代码后重新复现（这是因为代码久远，我记不得在哪里插入过消融实验的代码了，所以您可能正在运行消融实验）

谢谢您的回复～我看到https://github.com/xuuuluuu/SemEval-Triplet-data/tree/master/ASTE-Data-V2-EMNLP2020这个链接里下载到的数据包含train_triplets、dev_triplets、test_triplets三个split，您是把三个split数据合并后重新切分了train、dev、test是吗？

**Comment by chen1310054465** [comment]
抱歉   我看错项目了   数据应该是没有改动  那么您的性能差异应该是代码上的问题   您可以检查一下预处理、编码和解码部分是否有消融实验的代码遗留   这应该能解决您的问题   论文中的结果是5次实验后的平均结果（当然性能这东西有时候有点玄学，有些设备就是跑不高，换个种子试试？）

**Comment by ZayIsAllYouNeed** [comment]
> 抱歉 我看错项目了 数据应该是没有改动 那么您的性能差异应该是代码上的问题 您可以检查一下预处理、编码和解码部分是否有消融实验的代码遗留 这应该能解决您的问题 论文中的结果是5次实验后的平均结果（当然性能这东西有时候有点玄学，有些设备就是跑不高，换个种子试试？）

好的，谢谢佬～我再研究研究

**Comment by ZayIsAllYouNeed** [comment]
> 

佬，能再确认一点嘛：您在训练的130个epoch里使用dev来验证挑选最佳模型，然后在test上测试得到最后的指标对吗？

**Comment by ZayIsAllYouNeed** [comment]
> 抱歉 我看错项目了 数据应该是没有改动 那么您的性能差异应该是代码上的问题 您可以检查一下预处理、编码和解码部分是否有消融实验的代码遗留 这应该能解决您的问题 论文中的结果是5次实验后的平均结果（当然性能这东西有时候有点玄学，有些设备就是跑不高，换个种子试试？）


佬，能再确认一点嘛：您在训练的130个epoch里使用dev来验证挑选最佳模型，然后在test上测试得到最后的指标对吗？
